import SwiftUI

struct DisclaimersView: View {
    var body: some View {
        List {
            Section {
                VStack(alignment: .leading, spacing: 8) {
                    Text("MealSight is a nutrition tracking tool designed to help you understand your eating habits. It is not a medical device and is not intended to diagnose, treat, cure, or prevent any disease or health condition.")
                        .font(.subheadline)

                    Text("Always consult a qualified healthcare professional before making changes to your diet, especially if you have any medical conditions, allergies, or are taking medication.")
                        .font(.subheadline)
                }
                .foregroundStyle(.secondary)
            } header: {
                Label("Health Disclaimer", systemImage: "heart.text.square")
            }

            Section {
                VStack(alignment: .leading, spacing: 8) {
                    Text("Calorie and macronutrient estimates provided by MealSight are approximations generated using AI image analysis and the USDA FoodData Central database. These values may vary from actual nutritional content by up to 20% or more depending on factors including:")
                        .font(.subheadline)

                    VStack(alignment: .leading, spacing: 4) {
                        bulletPoint("Portion size estimation from photos")
                        bulletPoint("Food preparation methods and recipes")
                        bulletPoint("Ingredient variations between brands")
                        bulletPoint("Image quality and lighting conditions")
                    }

                    Text("For precise nutritional information, refer to product nutrition labels or consult a registered dietitian.")
                        .font(.subheadline)
                }
                .foregroundStyle(.secondary)
            } header: {
                Label("Accuracy of Estimates", systemImage: "info.circle")
            }

            Section {
                VStack(alignment: .leading, spacing: 8) {
                    Text("Meal suggestions, motivational tips, and nutritional guidance provided by the AI Coach feature are for informational purposes only. They do not constitute medical or dietary advice.")
                        .font(.subheadline)

                    Text("These suggestions are generated by an AI model and may not account for your specific health conditions, allergies, medications, or individual nutritional needs.")
                        .font(.subheadline)
                }
                .foregroundStyle(.secondary)
            } header: {
                Label("AI Coach Suggestions", systemImage: "brain.head.profile")
            }

            Section {
                VStack(alignment: .leading, spacing: 8) {
                    Text("When you scan a meal, photo, or label, the image is sent to Anthropic's Claude API for analysis. Anthropic processes this data to generate nutritional estimates and returns the results to your device.")
                        .font(.subheadline)

                    Text("Anthropic does not use API data to train AI models. Images are processed in real time and are not stored beyond what is needed to complete the request.")
                        .font(.subheadline)

                    Text("Your meal history, goals, and personal data are stored locally on your device and are not shared with third parties except when explicitly using AI analysis features.")
                        .font(.subheadline)
                }
                .foregroundStyle(.secondary)
            } header: {
                Label("AI Data Processing", systemImage: "lock.shield")
            }

            Section {
                VStack(alignment: .leading, spacing: 8) {
                    Text("Text food search results are provided by the USDA FoodData Central database. While the USDA is a trusted source, nutritional values may not perfectly match the specific product or preparation you consumed.")
                        .font(.subheadline)
                }
                .foregroundStyle(.secondary)
            } header: {
                Label("Data Sources", systemImage: "building.columns")
            }

            Section {
                Link(destination: URL(string: "https://nutrilens-api.nutrilens.workers.dev/privacy")!) {
                    Label("Privacy Policy", systemImage: "hand.raised.fill")
                }

                Link(destination: URL(string: "https://nutrilens-api.nutrilens.workers.dev/terms")!) {
                    Label("Terms of Service", systemImage: "doc.text")
                }
            } header: {
                Label("Legal", systemImage: "scale.3d")
            }
        }
        .navigationTitle("Disclaimers & Legal")
    }

    private func bulletPoint(_ text: String) -> some View {
        HStack(alignment: .top, spacing: 6) {
            Text("\u{2022}")
                .font(.subheadline)
            Text(text)
                .font(.subheadline)
        }
    }
}

#Preview {
    NavigationStack {
        DisclaimersView()
    }
}
